spring:
  application:
    name: spring-jpa
  web:
    error:
      include-stacktrace: on_param
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_db?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=America/Sao_Paulo&createDatabaseIfNotExist=true
    username: root
    password: dev_jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  threads:
    virtual:
      enabled: true
logging:
  level:
   study.ronoyaro: debug
server:
  servlet:
    context-path: /
